### ISSUE TITLE
Add support to release linux aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [osqp/qdldl-python#17]
Problem
---------
On aarch64, `pip install qdldl` builds the wheels from source code and then installs it. It requires the user to have a development environment installed on their system. Also, it takes more time to build the wheels than downloading and extracting the wheels from PyPI.

Resolution
-----------
On aarch64, `pip install qdldl` should download the wheels from PyPI.

@bstellato, Please let me know your interest in releasing aarch64 wheels. I can help with this.

**Comment by imciner2** [comment]
aarch64 linux wheels are now available on PyPi after the recent refactor of the CI pipelines.
