### ISSUE TITLE
Release of 0.1.6?

### ISSUE THREAD

**Issue by h-vetinari** [osqp/qdldl-python#23]
Is there going to be a release of the python wrappers corresponding to https://github.com/osqp/qdldl/releases/tag/v0.1.6 (or are the current wrappers compatible with that version)?

**Comment by h-vetinari** [comment]
Gentle ping @bstellato @vineetbansal

**Comment by vineetbansal** [comment]
@imciner2 - I'm not familiar with the `qdldl` codebase, but looks like all the commits made to it since the last python wrapper release are for internal refactoring and does not affect the wrappers? Here are the commit messages:
```
29d1404 (HEAD -> master, tag: v0.1.6, origin/master, origin/HEAD) Merge pull request #46 from osqp/im/release-0.1.6
c79876a Update changelog for 0.1.6 release
a85dd0e Add changelog entry for 0.1.5
735a65f Cleanup changelog formatting
bc09f4c Merge pull request #45 from osqp/im/cmakeoption
f7df6d3 Update readme wth CMake option name changes
2a4326a Rename Cmake options to have QDLDL prefix for namespacing
f2665f8 Merge pull request #38 from imciner2/im/disabletargets
9fae555 Rename the new cmake variable to not have the D in it
7000450 Fix merge error (missing rename of UNITTESTS -> QDLDL_UNITTESTS)
207dd56 Add shared and static library options to CI build matrix
12c2c17 Merge branch master into im/disabletargets
c662639 Merge pull request #37 from imciner2/im/confheader
2514515 Remove old header file from gitignore
1bf23f3 Move the new defines into the existing types file
e96f114 Merge branch 'master' into im/confheader
5808ef9 Merge pull request #36 from imciner2/im/visibility
89f748c Merge branch 'master' into im/visibility
3f7a975 Merge pull request #41 from osqp/im/badge_update
f6be2b7 oxfordcontrol -> osqp
c652d13 Update readme badges
9526d6a Merge branch 'master' into im/visibility
715d8d5 Merge pull request #39 from imciner2/im/ghactions
c48b441 Disable coverage in the config builds
6d02e16 Pin lcov action and add coveralls upload action
b286130 Remove Travis and Appveyor CI, since we use GitHub actions instead
10943fa Add coverage on Linux only
bfa44a0 Add workflow to test possible build configurations
6b48c03 Add basic GitHub actions workflow
31ef42f Add symbol visibility information to all the functions that are exported
a5c4739 The unit tests should be guarded by the static lib flag
86f623c Change how the build options are displayed
5e90d27 Use the option flag for the CMake options
0d0289b Put the QDLDL unit testing executable behind a better flag
aa3e15f Cleanup some Cmake formatting
28235d7 Gate the library products behind Cmake flags
ee49e65 Generate a header containing the private QDLDL config options
a00d500 Merge pull request #33 from imciner2/im/cmakefix
634fd4b Merge branch 'master' into im/cmakefix
6a8a387 Merge pull request #34 from oxfordcontrol/update_readme
1f26f6c (origin/update_readme) Updated OSQP bibtex entry
ef1cf4f Add defines to allow getting the QDLDL version in consuming software
f259d3f Fix the install directory for cmake files and install a version file
```

I'm certainly able to build/install and run the tests successfully, when I update the `qdldl` git submodule to tag `v0.1.6`.
If so, maybe we can do a new release?

**Comment by imciner2** [comment]
@vineetbansal 

> I'm not familiar with the qdldl codebase, but looks like all the commits made to it since the last python wrapper release are for internal refactoring and does not affect the wrapper?

The only one that might affect the wrappers would be the CMake variable renaming, where I removed the `D` prefix from the CMake variables and also prefixed them with `QDLDL`. So that means if you used to specify `-DDFLOAT=` on the CMake command line to build, it needs to change to be `-DQDLDL_FLOAT=` in order for the build to be the same.

Other than that, it should be the same API for the interfaces.

**Comment by vineetbansal** [comment]
@imciner2 - thanks. I ran a `grep` on the code and I'm not seeing any use of `DLFOAT/DLONG` in the wrappers, but did notice `UNITTESTS` (now `OSQP_UNITTESTS`) so I'll change that. I'll update the git submodule to use the latest tag (pending PR 48 on `qdldl`) and bump this version to match `qdldl`s.

I also notice that there's an unused submodule here (redundant after its was moved):
https://github.com/osqp/qdldl-python/blob/8211ee6f2338232b7763596659fd69f6a7d1dcc4/.gitmodules#L1

So I can remove that, unless I'm missing something.

**Comment by vineetbansal** [comment]
We've release a version 1.0.7 of qdldl on pypi to match the corresponding version release of qdldl.

**Comment by h-vetinari** [comment]
> We've released a version 1.0.7 of qdldl on pypi to match the corresponding version release of qdldl.

Thanks! Do you mean 1.7.0? (Seeing that this version was just released for qdldl)

**Comment by bperkins24** [comment]
Looks like 0.1.7 and can confirm works fine for me.  Thanks all!

**Comment by vineetbansal** [comment]
Yes - `0.1.7`, not `1.0.7`. Sorry for the typo there. I'm closing this issue, but feel free to open a new one if there are issues with the new release.
