### ISSUE TITLE
error on installing mac M1 computer

### ISSUE THREAD

**Issue by abybordi** [osqp/qdldl-python#24]
I have problem pip installing qdldl on a mac M1 computer and the error doesn't seem to be an error of pip itself. here is what I get:

The C compiler      
                "/usr/bin/cc"
      
              is not able to compile a simple test program.
      
              It fails with the following output:
      
                Change Dir: /private/var/folders/3f/r0wbc5md3fd4qrrzdynqrtzm0000gn/T/pip-install-amewv_ax/qdldl_63c594913c0d4f96b904a16463ca161e/c/build/CMakeFiles/CMakeTmp
      
                Run Build Command(s):/usr/bin/make -f Makefile cmTC_49737/fast && xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
      
      
      
      
      
              CMake will not be able to correctly generate this project.
            Call Stack (most recent call first):
              CMakeLists.txt:4 (project)
      
      
            -- Configuring incomplete, errors occurred!
            See also "/private/var/folders/3f/r0wbc5md3fd4qrrzdynqrtzm0000gn/T/pip-install-amewv_ax/qdldl_63c594913c0d4f96b904a16463ca161e/c/build/CMakeFiles/CMakeOutput.log".
            See also "/private/var/folders/3f/r0wbc5md3fd4qrrzdynqrtzm0000gn/T/pip-install-amewv_ax/qdldl_63c594913c0d4f96b904a16463ca161e/c/build/CMakeFiles/CMakeError.log".
            xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
            building 'qdldl' extension
            creating build
            creating build/temp.macosx-11.1-arm64-cpython-38
            creating build/temp.macosx-11.1-arm64-cpython-38/cpp
         note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for qdldl
        Running setup.py clean for qdldl
      Failed to build qdldl
      Installing collected packages: wheel, typing-extensions, tomli, setuptools, pyparsing, numpy, scipy, packaging, oldest-supported-numpy, setuptools_scm, qdldl
        Running setup.py install for qdldl: started
        Running setup.py install for qdldl: finished with status 'error'
        error: subprocess-exited-with-error
      
        × Running setup.py install for qdldl did not run successfully.
        │ exit code: 1
        ╰─> [44 lines of output]
            running install

miniforge3/envs/ninen/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
              warnings.warn(
            running build
            running build_ext
            -- The C compiler identification is unknown
            -- The CXX compiler identification is unknown
            -- Detecting C compiler ABI info
            -- Detecting C compiler ABI info - failed
            -- Check for working C compiler: /usr/bin/cc
            -- Check for working C compiler: /usr/bin/cc - broken
The C compiler
      
                "/usr/bin/cc"
      
              is not able to compile a simple test program.
      
              It fails with the following output:
      
                Change Dir: /private/var/folders/3f/r0wbc5md3fd4qrrzdynqrtzm0000gn/T/pip-install-amewv_ax/qdldl_63c594913c0d4f96b904a16463ca161e/c/build/CMakeFiles/CMakeTmp
      
                Run Build Command(s):/usr/bin/make -f Makefile cmTC_a7ccf/fast && xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
      
      
      
              CMake will not be able to correctly generate this project.
            Call Stack (most recent call first):
              CMakeLists.txt:4 (project)
      
      
            -- Configuring incomplete, errors occurred!
            See also "/private/var/folders/3f/r0wbc5md3fd4qrrzdynqrtzm0000gn/T/pip-install-amewv_ax/qdldl_63c594913c0d4f96b904a16463ca161e/c/build/CMakeFiles/CMakeOutput.log".
            See also "/private/var/folders/3f/r0wbc5md3fd4qrrzdynqrtzm0000gn/T/pip-install-amewv_ax/qdldl_63c594913c0d4f96b904a16463ca161e/c/build/CMakeFiles/CMakeError.log".
            xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
            building 'qdldl' extension
            creating build
            creating build/temp.macosx-11.1-arm64-cpython-38
         xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
            error: command '/usr/bin/gcc' failed with exit code 1
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: legacy-install-failure
      
      × Encountered error while trying to install package.
      ╰─> qdldl
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for output from the failure.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
 See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by tpilewicz** [comment]
Have you correctly installed the Command line tools?

```
xcode-select --install
```

**Comment by h-vetinari** [comment]
You can install for osx-arm (=M1) using conda
```
conda install -c conda-forge qdldl-python
```

**Comment by imciner2** [comment]
We now provide precompiled wheels for macOS arm processors through pip.
