### ISSUE TITLE
DLL load failing for OSQP solver in version 0.1.5.post2

### ISSUE THREAD

**Issue by grgmiller** [osqp/qdldl-python#28]
When using `cvxpy` for optimization, I am getting the following error message:
```
(CVXPY) Dec 20 02:25:38 PM: Encountered unexpected exception importing solver OSQP:
ImportError('DLL load failed while importing qdldl: The specified module could not be found.')
```
This error only occurs when `qdldl-python==0.1.5.post2`. If I update my conda environment to `qdldl-python==0.1.5`, it fixes the issue, which suggests that the issue might be resulting from the post2 release of qdldl.

See also: https://github.com/cvxpy/cvxpy/issues/1946

**Comment by imciner2** [comment]
We are now up to 0.1.7.post versions of qdldl, so closing this as possibly outdated. If this still occurs, please let us know.

**Comment by peekxc** [comment]
I can confirm this is still an issue with the current version (0.1.7); I was only able to load cvxpy by installing `qdldl-0.1.5`
