### ISSUE TITLE
Add arm64 macOS wheel?

### ISSUE THREAD

**Issue by akshayka** [osqp/qdldl-python#35]
Hi!

Would it be possible to build and publish `arm64` wheels to PyPI? Right now, on Apple Silicon, pip installing `qdldl` (or `OSQP`) triggers a build from source, which fails if the user doesn't have `cmake` installed.

`cibuildhwheel` supports building `arm64` wheels: https://cibuildwheel.readthedocs.io/en/stable/faq/#apple-silicon

**Comment by imciner2** [comment]
macOS arm64 wheels are now available through PyPi.
