### ISSUE TITLE
Getting a good solution with qdldl

### ISSUE THREAD

**Issue by ipa-danb** [osqp/qdldl-python#45]
I seem to have a problem of getting a good solution with qdldl that is comparable to a solution i get with SVD solve.

Code looks like this: 

```py
import numpy as np
from scipy.linalg import svd
import qdldl
from scipy import sparse
def solve_svd(A, b):
    # compute svd of A
    U, s, Vh = svd(A)
    c = np.dot(U.T, b)
    w = np.dot(np.diag(1 / s), c)
    x = np.dot(Vh.conj().T, w)
    return x.flatten()


def create_test_case(n: int = 100) -> (np.array, np.array):
    A = np.random.random((n, n))
    b = np.random.random((n, 1))
    return A, b


def solve_qdl(A, b):
    A = sparse.csc_matrix(A)
    F = qdldl.Solver(A)
    x = F.solve(b)
    return x

n = 4

A,b = create_test_case(n)

x_qdl = solve_qdl(A,b)
x_svd = solve_svd(A,b)

print(f"A:\n{A},\n b:\n{b}")

print(x_qdl)
print(A.dot(x_qdl) - b.flatten())
print(np.linalg.norm(A.dot(x_qdl) - b.flatten()))
print(A.dot(x_svd) - b.flatten())
print(np.linalg.norm(A.dot(x_svd) - b.flatten()))
```

My results are 

```
A:
[[0.94018968 0.44976538 0.64800948 0.50945055]
 [0.83979975 0.32532913 0.04971389 0.39696991]
 [0.22446993 0.86123995 0.60444106 0.32031031]
 [0.61156876 0.72162649 0.41970631 0.15859167]],
 b:
[[0.43597714]
 [0.77745818]
 [0.36896826]
 [0.48432174]]

[ 9.95054186 -3.83844654 -6.93219554 -5.30157607]

[ 1.55431223e-15  3.88105327e+00 -7.32944747e+00 -9.19077944e-01]

8.344344129323519

[ 1.66533454e-16 -1.11022302e-16  0.00000000e+00 -2.22044605e-16]

2.9893669801409083e-16

```

So with qdldl i get a result that is magnitudes away from the result of SVD, but im not quite sure why that is? Am i doing something wrong?

**Comment by imciner2** [comment]
It doesn't look like you are ensuring A is a symmetric matrix in your example. QDLDL is an LDL^T solver, which means that it is specialised to operate on real symmetric matrices, so internally, when passed a full matrix we throw away the lower triangular half and only use the upper triangular half. Your SVD approach doesn't assume symmetry.

**Comment by ipa-danb** [comment]
> It doesn't look like you are ensuring A is a symmetric matrix in your example. QDLDL is an LDL^T solver, which means that it is specialised to operate on real symmetric matrices, so internally, when passed a full matrix we throw away the lower triangular half and only use the upper triangular half. Your SVD approach doesn't assume symmetry.

Ah, dang, i had a feeling it was something very obvious. Thank you! When i ensure symmetry i get comparable results now!
